//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BareSurf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BareSurf.StaticText", typeof(StaticText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLbl {
            get {
                return ResourceManager.GetString("BackLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse→.
        /// </summary>
        public static string BrowseLbl {
            get {
                return ResourceManager.GetString("BrowseLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be done.
        /// </summary>
        public static string CanBeDoneLbl {
            get {
                return ResourceManager.GetString("CanBeDoneLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://duckduckgo.com/?q=.
        /// </summary>
        public static string DefaultSearchPage {
            get {
                return ResourceManager.GetString("DefaultSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed.
        /// </summary>
        public static string Executed {
            get {
                return ResourceManager.GetString("Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ForwardLbl {
            get {
                return ResourceManager.GetString("ForwardLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://duckduckgo.com/.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string NewTabLbl {
            get {
                return ResourceManager.GetString("NewTabLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        public static string RemoveTabLbl {
            get {
                return ResourceManager.GetString("RemoveTabLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLbl {
            get {
                return ResourceManager.GetString("SettingsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Status Bar.
        /// </summary>
        public static string ShowStatusBarLbl {
            get {
                return ResourceManager.GetString("ShowStatusBarLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
    }
}
